const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',

    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',


    FETCH_FOODS: 'FETCH_FOODS',
    FETCH_FOOD: 'FETCH_FOOD',
    SET_FOOD: 'SET_FOOD',

    FETCH_CHARITY: 'FETCH_CHARITY',
    FETCH_CHARITIES: 'FETCH_CHARITIES',
    SET_CHARITY: 'SET_CHARITY'
}

export default Constants;
