const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',

    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',

    FETCH_FOOD: 'FETCH_FOOD',
    FETCH_FOODS: 'FETCH_FOODS',
    SET_FOODS: 'SET_FOOD',
<<<<<<< HEAD

    FETCH_CHARITY: 'FETCH_CHARITY',
    FETCH_CHARITIES: 'FETCH_CHARITIES'
=======
    ADD_CART: 'ADD_CART'
>>>>>>> cf5c5b4be67f303efb3f486250d19fe4c35cea1f
}

export default Constants;
