const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',

    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',

    FETCH_FOOD: 'FETCH_FOOD',
    FETCH_FOODS: 'FETCH_FOODS',
    SET_FOODS: 'SET_FOOD',
    ADD_CART: 'ADD_CART'
}

export default Constants;
